ktor:
    application:
        modules:
            - kg.erkan.ApplicationKt.module
    development: ${DEVELOPMENT:false}
    deployment:
        port: ${PORT:8080}
        host: ${HOST:0.0.0.0}

jwt:
    secret: ${JWT_SECRET:"your-super-secret-jwt-key-change-in-production"}
    issuer: ${JWT_ISSUER:"ktor-todo-api"}
    audience: ${JWT_AUDIENCE:"ktor-todo-users"}
    realm: ${JWT_REALM:"Todo API"}
    expirationTime: ${JWT_EXPIRATION:86400} # 24 hours in seconds

database:
    # PostgreSQL Database - Use environment variable or default for Docker
    url: ${DATABASE_URL:"jdbc:postgresql://postgres:5432/ktor_todo"}
    driver: "org.postgresql.Driver"
    user: ${DATABASE_USER:"postgres"}
    password: ${DATABASE_PASSWORD:"password"}
    maxPoolSize: 10
    autoCreateTables: true
