ktor:
    application:
        modules:
            - kg.erkan.ApplicationKt.module
    deployment:
        port: 8080

jwt:
    secret: ${JWT_SECRET:"your-super-secret-jwt-key-change-in-production"}
    issuer: "ktor-todo-api"
    audience: "ktor-todo-users"
    realm: "Todo API"
    expirationHours: 24

database:
    # H2 Database (in-memory, no setup required)
    url: ${DATABASE_URL:"jdbc:h2:mem:ktor_todo"}
    driver: "org.h2.Driver"
    user: ${DATABASE_USER:"sa"}
    password: ${DATABASE_PASSWORD:""}
    maxPoolSize: 10
    autoCreateTables: ${AUTO_CREATE_TABLES:true}
    
    # PostgreSQL (uncomment when Docker is available)
    # url: ${DATABASE_URL:"jdbc:postgresql://localhost:5432/ktor_todo"}
    # driver: "org.postgresql.Driver" 
    # user: ${DATABASE_USER:"postgres"}
    # password: ${DATABASE_PASSWORD:"password"}
